# config.yaml (edit only this file per experiment)
# data_module and data_class are optional; they will be inferred from folder name if omitted.
data_module: Function4DataHandler
data_class: Function4DataHandler

source_label: "week-x"
yield_col: "opt-place-score"

bayesopt:
  xi_values: [0.01, 0.1, 0.3]
  kappa_values: [1.0, 2.0, 3.0]
  grid_sizes: [200]
  methods: ["PI", "EI", "UCB"]
  apply_scaling: true
  filter_mode: "gp"
  downsample_grid: true     # to downsample or not.
  downsample_stride: 8            # higher stride means more downsampling.

model:
  type: cnn   # or "cnn"
  params:
    input_dim: 4
    lr: 0.001
    epochs: 600
    patience: 20

plot:
  scale_factor: 2000.0
  yield_scale_factor: 200.0
  source_color: red
  source_marker_style: "x"
  show_candidates: true   # <-- new flag
  figsize: [6, 5]
